import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  entries: ["./src/cli.mjs", "./bin/gitvan.mjs"],
  outDir: "dist",
  declaration: false,
  clean: true,
  failOnWarn: false,
  bundleless: false,

  rollup: {
    // UNRDF is a normal package dependency. The historical vendor/unrdf
    // submodule was deliberately removed; build identity follows the lockfile.
    external: [
      "node:fs",
      "node:path",
      "node:child_process",
      "node:os",
      "node:crypto",
      "node:util",
      "node:stream",
      "node:events",
      "node:buffer",
      "node:url",
      "node:querystring",
      "node:http",
      "node:https",
      "node:net",
      "node:tls",
      "node:zlib",
      "node:readline",
      "node:cluster",
      "node:worker_threads",
      "node:perf_hooks",
      "node:async_hooks",
      "node:timers",
      "node:tty",
      "node:vm",
      "node:assert",
      "node:fs/promises",
      "node:path/posix",
      "node:path/win32",
      "citty",
      "consola",
      "unctx",
      "pathe",
      "defu",
      "klona",
      "klona/full",
      "lru-cache",
      "zod",
      "tinyglobby",
      "gray-matter",
      "js-yaml",
      "json5",
      "inflection",
      "nunjucks",
      "hookable",
      "unrouting",
      "giget",
      "prompts",
      "minimatch",
      "semver",
      "n3",
      "@unrdf/core",
      "@unrdf/hooks",
      "@unrdf/kgn",
      "@unrdf/knowledge-engine",
      "@unrdf/observability",
      "@unrdf/streaming",
      "@unrdf/validation",
      "@babel/parser",
      "@babel/traverse",
      "fuse.js",
      "node-cron",
      "cacache",
      "toml",
      "p-queue",
      "exceljs",
      "marked",
      "fdir",
      "picomatch",
      "brace-expansion",
      "concat-map",
      "balanced-match",
      "@types/semver",
      "@types/node",
      "@ai-sdk/anthropic",
      "ollama",
      "ollama-ai-provider-v2",
      "memfs",
      "isomorphic-git",
      "ai",
      "ai/openai",
      "ai/anthropic",
    ],
    output: {
      preserveModules: false,
      format: "esm",
      entryFileNames: "[name].mjs",
      chunkFileNames: "[name]-[hash].mjs",
      assetFileNames: "[name]-[hash][extname]",
    },
    esbuild: {
      target: "node22",
      minify: process.env.NODE_ENV === "production",
      sourcemap: process.env.NODE_ENV !== "production",
      treeShaking: true,
      platform: "node",
      format: "esm",
    },
  },

  externals: [
    { input: "./templates", outDir: "./dist/templates" },
    { input: "./packs", outDir: "./dist/packs" },
    { input: "./types", outDir: "./dist/types" },
    { input: "./src/rdf/ontologies", outDir: "./dist/rdf/ontologies" },
    { input: "./src/git-native/queries", outDir: "./dist/git-native/queries" },
    { input: "./src/rdf/rules", outDir: "./dist/rdf/rules" },
  ],
});
