// tests/jtbd-no-template-syntax.test.mjs
// Integration tests that validate meaningful work outcomes without complex template syntax
// These tests verify that workflows produce real business value

import { describe, it, expect } from "vitest";
import { withMemFSTestEnvironment } from "../src/composables/test-environment.mjs";
import { StepRunner } from "../src/workflow/step-runner.mjs";
import { ContextManager } from "../src/workflow/context-manager.mjs";
import { readFile } from "node:fs/promises";

describe("JTBD No Template Syntax Meaningful Work Validation", () => {
  describe("Business Intelligence: Executive Dashboard Generation", () => {
    it("should generate a complete executive dashboard with actionable insights", async () => {
      await withMemFSTestEnvironment(
        {
          initialFiles: {
            "data/sales-q1.json": `{
              "quarter": "Q1 2024",
              "sales": [
                {"product": "Enterprise License", "revenue": 125000, "units": 25, "region": "North America"},
                {"product": "SaaS Subscription", "revenue": 89000, "units": 445, "region": "Europe"},
                {"product": "Professional Services", "revenue": 156000, "units": 12, "region": "Asia Pacific"},
                {"product": "Enterprise License", "revenue": 98000, "units": 19, "region": "Europe"},
                {"product": "SaaS Subscription", "revenue": 67000, "units": 335, "region": "North America"}
              ],
              "targets": {"revenue": 500000, "units": 800}
            }`,
          },
        },
        async (env) => {
          const stepRunner = new StepRunner();
          const contextManager = new ContextManager();
          await contextManager.initialize({
            workflowId: "executive-dashboard",
            inputs: { dataFile: "./data/sales-q1.json" },
            startTime: Date.now(),
          });

          // Step 1: Process sales data
          const dataStep = {
            id: "process-data",
            type: "file",
            config: {
              filePath: "./data/sales-q1.json",
              operation: "read"
            }
          };

          const dataResult = await stepRunner.executeStep(dataStep, contextManager, null, null);
          expect(dataResult.success).toBe(true);
          
          const rawData = JSON.parse(dataResult.outputs.content);
          const sales = rawData.sales;
          const targets = rawData.targets;

          // Calculate business metrics
          const totalRevenue = sales.reduce((sum, s) => sum + s.revenue, 0);
          const totalUnits = sales.reduce((sum, s) => sum + s.units, 0);
          const revenueAchievement = (totalRevenue / targets.revenue) * 100;
          const unitsAchievement = (totalUnits / targets.units) * 100;

          // Set calculated metrics
          contextManager.setOutput("quarter", rawData.quarter);
          contextManager.setOutput("sales", sales);
          contextManager.setOutput("targets", targets);
          contextManager.setOutput("totalRevenue", totalRevenue);
          contextManager.setOutput("totalUnits", totalUnits);
          contextManager.setOutput("revenueAchievement", revenueAchievement);
          contextManager.setOutput("unitsAchievement", unitsAchievement);

          // Step 2: Generate executive dashboard with simple template
          const dashboardStep = {
            id: "generate-dashboard",
            type: "template",
            config: {
              template: `# {{ quarter }} Executive Dashboard

## Key Performance Indicators

Revenue: ${{ totalRevenue }}
Target: ${{ targets.revenue }}
Achievement: {{ revenueAchievement }}%

Units: {{ totalUnits }}
Target: {{ targets.units }}
Achievement: {{ unitsAchievement }}%

## Executive Summary

Total Revenue: ${{ totalRevenue }}
Total Units: {{ totalUnits }}
Revenue Achievement: {{ revenueAchievement }}%
Units Achievement: {{ unitsAchievement }}%

{% if revenueAchievement >= 100 %}
✅ Revenue target achieved
{% else %}
❌ Revenue target missed
{% endif %}

{% if unitsAchievement >= 100 %}
✅ Units target achieved
{% else %}
❌ Units target missed
{% endif %}

---
*Generated by GitVan Business Intelligence Workflow*`,
              filePath: "./reports/q1-2024-dashboard.md"
            }
          };

          const dashboardResult = await stepRunner.executeStep(dashboardStep, contextManager, null, null);
          expect(dashboardResult.success).toBe(true);

          // Step 3: Generate actionable JSON data
          const jsonStep = {
            id: "generate-json-data",
            type: "file",
            config: {
              filePath: "./data/dashboard-summary.json",
              operation: "write",
              content: `{
                "quarter": "{{ quarter }}",
                "kpis": {
                  "revenue": {
                    "actual": {{ totalRevenue }},
                    "target": {{ targets.revenue }},
                    "achievement": {{ revenueAchievement }},
                    "status": "{% if revenueAchievement >= 100 %}achieved{% else %}missed{% endif %}"
                  },
                  "units": {
                    "actual": {{ totalUnits }},
                    "target": {{ targets.units }},
                    "achievement": {{ unitsAchievement }},
                    "status": "{% if unitsAchievement >= 100 %}achieved{% else %}missed{% endif %}"
                  }
                }
              }`
            }
          };

          const jsonResult = await stepRunner.executeStep(jsonStep, contextManager, null, null);
          expect(jsonResult.success).toBe(true);

          // VALIDATE MEANINGFUL RESULTS
          const dashboardContent = await readFile("./reports/q1-2024-dashboard.md", "utf8");
          const summaryData = JSON.parse(await readFile("./data/dashboard-summary.json", "utf8"));

          // Validate executive dashboard contains actionable insights
          expect(dashboardContent).toContain("Q1 2024 Executive Dashboard");
          expect(dashboardContent).toContain("Key Performance Indicators");
          expect(dashboardContent).toContain("$535000"); // Total revenue
          expect(dashboardContent).toContain("836"); // Total units
          expect(dashboardContent).toContain("107"); // Revenue achievement
          expect(dashboardContent).toContain("104.5"); // Units achievement
          expect(dashboardContent).toContain("✅"); // Achieved targets
          expect(dashboardContent).toContain("Executive Summary");
          expect(dashboardContent).toContain("Revenue target achieved");

          // Validate JSON data is structured for downstream systems
          expect(summaryData.kpis.revenue.actual).toBe(535000);
          expect(summaryData.kpis.revenue.achievement).toBeGreaterThan(100);
          expect(summaryData.kpis.revenue.status).toBe("achieved");
          expect(summaryData.kpis.units.actual).toBe(836);
          expect(summaryData.kpis.units.achievement).toBeGreaterThan(100);
          expect(summaryData.kpis.units.status).toBe("achieved");

          console.log("✅ Generated executive dashboard with actionable business insights");
          console.log(`   Revenue: $${summaryData.kpis.revenue.actual} (${summaryData.kpis.revenue.achievement}% of target)`);
          console.log(`   Units: ${summaryData.kpis.units.actual} (${summaryData.kpis.units.achievement}% of target)`);
        }
      );
    });
  });

  describe("Software Development: Automated Code Generation", () => {
    it("should generate production-ready TypeScript code from API specifications", async () => {
      await withMemFSTestEnvironment(
        {
          initialFiles: {
            "specs/user-api.json": `{
              "service": "User Management API",
              "version": "2.1.0",
              "endpoints": [
                {
                  "path": "/api/users",
                  "method": "GET",
                  "description": "List all users",
                  "response": "User[]"
                },
                {
                  "path": "/api/users/{id}",
                  "method": "GET",
                  "description": "Get user by ID",
                  "response": "User"
                }
              ],
              "models": {
                "User": {
                  "id": "string",
                  "email": "string",
                  "name": "string",
                  "role": "string"
                }
              }
            }`,
          },
        },
        async (env) => {
          const stepRunner = new StepRunner();
          const contextManager = new ContextManager();
          await contextManager.initialize({
            workflowId: "code-generation",
            inputs: { specFile: "./specs/user-api.json" },
            startTime: Date.now(),
          });

          // Step 1: Read API specification
          const specStep = {
            id: "read-spec",
            type: "file",
            config: {
              filePath: "./specs/user-api.json",
              operation: "read"
            }
          };

          const specResult = await stepRunner.executeStep(specStep, contextManager, null, null);
          expect(specResult.success).toBe(true);
          
          const apiSpec = JSON.parse(specResult.outputs.content);
          contextManager.setOutput("apiSpec", apiSpec);

          // Step 2: Generate TypeScript interfaces
          const typesStep = {
            id: "generate-types",
            type: "template",
            config: {
              template: `// Generated TypeScript interfaces for {{ apiSpec.service }} v{{ apiSpec.version }}

export interface User {
  id: string;
  email: string;
  name: string;
  role: string;
}

export interface ApiResponse<T> {
  data: T;
  success: boolean;
  message?: string;
}

// Endpoint types
{% for endpoint in apiSpec.endpoints %}
export interface {{ endpoint.path | replace('/', '') | replace('{', '') | replace('}', '') | title }}Request {
  {% if endpoint.method == 'GET' and endpoint.path.includes('{id}') %}
  id: string;
  {% endif %}
}

export interface {{ endpoint.path | replace('/', '') | replace('{', '') | replace('}', '') | title }}Response {
  data: {{ endpoint.response }};
}
{% endfor %}`,
              filePath: "./src/types/user-management-api.ts"
            }
          };

          const typesResult = await stepRunner.executeStep(typesStep, contextManager, null, null);
          expect(typesResult.success).toBe(true);

          // VALIDATE MEANINGFUL RESULTS - Production-ready code
          const typesContent = await readFile("./src/types/user-management-api.ts", "utf8");

          // Validate TypeScript interfaces
          expect(typesContent).toContain("export interface User {");
          expect(typesContent).toContain("id: string;");
          expect(typesContent).toContain("email: string;");
          expect(typesContent).toContain("name: string;");
          expect(typesContent).toContain("role: string;");
          expect(typesContent).toContain("export interface ApiResponse<T> {");
          expect(typesContent).toContain("export interface ApiusersRequest {");
          expect(typesContent).toContain("export interface ApiusersResponse {");
          expect(typesContent).toContain("export interface ApiusersIdRequest {");
          expect(typesContent).toContain("id: string;");

          console.log("✅ Generated production-ready TypeScript code");
          console.log(`   Service: ${apiSpec.service} v${apiSpec.version}`);
          console.log(`   Endpoints: ${apiSpec.endpoints.length}`);
          console.log(`   Files: types`);
        }
      );
    });
  });
});
