/**
 * Example usage of the GitVan Idempotency and Rollback System
 *
 * This example demonstrates how to use the idempotency system
 * to safely install and manage packs with automatic rollback capabilities.
 */

import { createPackIdempotency } from './integration.mjs';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'pathe';
import { createLogger } from "../../utils/logger.mjs";
const logger = createLogger("pack:idempotency:example");

// Example pack installation with idempotency
async function examplePackInstallation() {
  logger.info('🚀 GitVan Idempotency System Example\n');

  // Create idempotency system
  const idempotency = createPackIdempotency({
    stateDir: '.gitvan/state',
    backupDir: '.gitvan/backups'
  });

  // Example pack specification
  const packSpec = {
    id: 'example-config-pack',
    version: '1.2.0',
    source: 'local',
    transforms: [
      {
        kind: 'json-merge',
        target: 'package.json',
        spec: {
          scripts: {
            'example:start': 'node src/example.mjs',
            'example:test': 'vitest run'
          }
        }
      }
    ],
    options: {
      backup: true,
      skipIfExists: false
    }
  };

  const targetFiles = ['package.json', 'src/example.mjs'];

  try {
    logger.info('1️⃣ Checking if pack installation should be skipped...');

    // Track the installation operation
    const tracking = await idempotency.trackPackInstallation(packSpec, './');

    if (tracking.shouldSkip) {
      logger.info('✅ Pack already installed with same configuration');
      logger.info('   Fingerprint:', tracking.fingerprint);
      return;
    }

    logger.info('2️⃣ Creating pre-installation snapshots...');

    // Create snapshots of files that might be modified
    const snapshots = await idempotency.createPreInstallSnapshots(targetFiles);
    logger.info(`   Created ${snapshots.size} snapshots`);

    logger.info('3️⃣ Applying pack transformations...');

    // Simulate pack installation
    const artifacts = await simulatePackInstallation(packSpec);
    logger.info(`   Applied ${artifacts.length} transformations`);

    logger.info('4️⃣ Recording successful installation...');

    // Record the installation
    const receipt = await idempotency.recordPackInstallation(
      packSpec,
      tracking.fingerprint,
      artifacts,
      snapshots
    );

    logger.info('✅ Pack installation completed successfully');
    logger.info('   Pack ID:', receipt.packId);
    logger.info('   Version:', receipt.version);
    logger.info('   Artifacts:', receipt.artifacts.length);
    logger.info('   Installed at:', receipt.installedAt);

    logger.info('\n5️⃣ Demonstrating rollback capability...');

    // Show how to rollback
    await demonstrateRollback(idempotency, packSpec.id);

  } catch (error) {
    logger.error('❌ Pack installation failed:', error.message);

    // In a real scenario, you might want to rollback any partial changes
    logger.info('🔄 Attempting to rollback partial changes...');

    try {
      const results = await idempotency.rollbackPack(packSpec.id);
      if (results.errors.length === 0) {
        logger.info('✅ Rollback completed successfully');
      } else {
        logger.info('⚠️ Rollback completed with errors:', results.errors);
      }
    } catch (rollbackError) {
      logger.error('❌ Rollback failed:', rollbackError.message);
    }
  }
}

// Simulate applying pack transformations
async function simulatePackInstallation(packSpec) {
  const artifacts = [];

  for (const transform of packSpec.transforms) {
    if (transform.kind === 'json-merge' && transform.target === 'package.json') {
      // Read current package.json
      const packagePath = 'package.json';
      let packageData = {};

      if (existsSync(packagePath)) {
        packageData = JSON.parse(readFileSync(packagePath, 'utf8'));
      }

      // Apply merge transformation
      if (!packageData.scripts) {
        packageData.scripts = {};
      }

      Object.assign(packageData.scripts, transform.spec.scripts);

      // Write updated package.json
      writeFileSync(packagePath, JSON.stringify(packageData, null, 2));

      artifacts.push({
        type: 'transform',
        path: packagePath,
        transform: {
          kind: 'json-merge',
          spec: transform.spec,
          original: packageData.scripts
        }
      });
    }
  }

  // Create example file
  const examplePath = join('src', 'example.mjs');
  const exampleContent = `// Generated by ${packSpec.id}@${packSpec.version}
logger.info('Hello from example pack!');
`;

  writeFileSync(examplePath, exampleContent);

  artifacts.push({
    type: 'file',
    path: examplePath,
    hash: null // Would be calculated in real implementation
  });

  return artifacts;
}

// Demonstrate rollback functionality
async function demonstrateRollback(idempotency, packId) {
  try {
    logger.info('   Creating rollback plan...');

    const plan = await idempotency.createPackRollbackPlan(packId);
    logger.info(`   Plan created with ${plan.steps.length} steps:`);

    for (const step of plan.steps) {
      logger.info(`     - ${step.action}: ${step.path} (${step.reason})`);
    }

    logger.info('   Executing rollback...');

    const results = await idempotency.rollbackPack(packId);

    if (results.errors.length === 0) {
      logger.info('   ✅ Rollback completed successfully');
      logger.info('   Success operations:', results.success.length);
    } else {
      logger.info('   ⚠️ Rollback completed with errors');
      logger.info('   Success operations:', results.success.length);
      logger.info('   Error operations:', results.errors.length);
    }

    logger.info('\n6️⃣ Verifying rollback...');

    const isInstalled = await idempotency.isPackInstalled(packId);
    logger.info('   Pack still installed:', isInstalled);

  } catch (error) {
    logger.error('   ❌ Rollback demonstration failed:', error.message);
  }
}

// Example of pack management operations
async function examplePackManagement() {
  logger.info('\n📋 Pack Management Operations\n');

  const idempotency = createPackIdempotency();

  // List installed packs
  logger.info('1️⃣ Listing installed packs...');
  const packs = idempotency.listInstalledPacks();
  logger.info(`   Found ${packs.length} installed packs:`);

  for (const pack of packs) {
    logger.info(`     - ${pack.id}@${pack.version} (${pack.artifactCount} artifacts)`);
  }

  // Validate pack integrity
  if (packs.length > 0) {
    logger.info('\n2️⃣ Validating pack integrity...');

    for (const pack of packs) {
      const validation = await idempotency.validatePackIntegrity(pack.id);

      if (validation.valid) {
        logger.info(`   ✅ ${pack.id}: Valid (${validation.artifactCount} artifacts)`);
      } else {
        logger.info(`   ❌ ${pack.id}: Invalid (${validation.issues.length} issues)`);
        for (const issue of validation.issues) {
          logger.info(`       - ${issue}`);
        }
      }
    }
  }

  // Export state for backup
  logger.info('\n3️⃣ Exporting state for backup...');
  const state = idempotency.exportState();
  logger.info(`   Exported state with ${Object.keys(state.packs).length} packs`);
  logger.info(`   Operations history: ${state.operations.length} entries`);

  // Cleanup old data
  logger.info('\n4️⃣ Cleaning up old data...');
  await idempotency.cleanup(30); // Keep 30 days
  logger.info('   Cleanup completed');
}

// Run the examples
if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    await examplePackInstallation();
    await examplePackManagement();

    logger.info('\n🎉 Idempotency system demonstration completed!');
  } catch (error) {
    logger.error('\n💥 Example failed:', error);
    await exitWithError(new Error("Operation failed"), 1);
  }
}