// src/jobs/job-bridge.mjs
// GitVan v3.0.0 — Job Bridge
// Adapts between GitVan job interface and Bree scheduler

import { join } from "pathe";
import { writeFileSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { createHash } from "node:crypto";
import { getBreeScheduler } from "./bree-scheduler.mjs";
import { useLock } from "../composables/lock.mjs";
import { useReceipt } from "../composables/receipt.mjs";
import { useGit } from "../composables/git/index.mjs";
import { createLogger } from "../utils/logger.mjs";

const logger = createLogger("jobs:bridge");

/**
 * Job Bridge
 * Converts GitVan job definitions to Bree-compatible format
 * Handles context passing, locking, and receipts
 *
 * NOTE: Composables (lock, receipt, git) are initialized lazily to preserve unctx context
 */
export class JobBridge {
  constructor(options = {}) {
    this.cwd = options.cwd || process.cwd();
    this.scheduler = getBreeScheduler({ cwd: this.cwd, ...options });

    // Lazy initialization - composables will be created on first use
    this._lock = null;
    this._receipt = null;
    this._git = null;

    this.workerDir = options.workerDir || join(this.cwd, ".gitvan", "workers");
    this.jobContexts = new Map();
    this.createdWorkerFiles = new Set(); // Track generated worker files for cleanup

    // Ensure worker directory exists
    if (!existsSync(this.workerDir)) {
      mkdirSync(this.workerDir, { recursive: true });
    }
  }

  /**
   * Get lock composable (lazy initialization)
   */
  get lock() {
    if (!this._lock) {
      this._lock = useLock();
    }
    return this._lock;
  }

  /**
   * Get receipt composable (lazy initialization)
   */
  get receipt() {
    if (!this._receipt) {
      this._receipt = useReceipt();
    }
    return this._receipt;
  }

  /**
   * Get git composable (lazy initialization)
   */
  get git() {
    if (!this._git) {
      this._git = useGit();
    }
    return this._git;
  }

  /**
   * Convert GitVan job definition to Bree job config
   */
  toBreeJobConfig(jobDef, options = {}) {
    const { cron, interval, timeout } = options;

    // Determine scheduling config from job definition or options
    const scheduleConfig = {};
    if (jobDef.cron || cron) {
      scheduleConfig.cron = jobDef.cron || cron;
    } else if (jobDef.interval || interval) {
      scheduleConfig.interval = jobDef.interval || interval;
    }

    // Create worker path
    const workerPath = this.createWorkerFile(jobDef);

    return {
      name: jobDef.id || jobDef.name || jobDef.meta?.name,
      path: workerPath,
      ...scheduleConfig,
      ...(timeout ? { timeout } : {}),
      worker: {
        workerData: {
          jobId: jobDef.id || jobDef.name || jobDef.meta?.name,
          jobFile: jobDef.file,
          meta: jobDef.meta,
        },
      },
    };
  }

  /**
   * Create a worker file for the job
   * Worker files are ES modules that Bree can execute in worker threads
   */
  createWorkerFile(jobDef) {
    const jobId = jobDef.id || jobDef.name || jobDef.meta?.name;
    const workerFileName = `${jobId.replace(/[:/]/g, "-")}-worker.mjs`;
    const workerPath = join(this.workerDir, workerFileName);

    // Worker template that imports and executes the job
    const workerContent = `
// Auto-generated worker for job: ${jobId}
// Generated by GitVan Job Bridge
import { parentPort, workerData } from 'worker_threads';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function runJob() {
  try {
    // Import the job definition using file:// URL
    const fileUrl = 'file://' + (process.platform === 'win32' ? '/' : '') + '${jobDef.file.replace(/\\\\/g, "/")}';
    const jobModule = await import(fileUrl);

    // Get the job definition
    const jobDef = jobModule.default || jobModule;

    // Get run function
    const runFn = jobDef.run || jobDef;

    if (typeof runFn !== 'function') {
      throw new Error('Job does not export a run function');
    }

    // Get context from workerData
    const context = workerData.context || {};
    const payload = workerData.payload || {};

    // Execute the job
    const result = await runFn({ payload, ctx: context, context });

    // Send success message
    if (parentPort) {
      parentPort.postMessage({
        type: 'success',
        jobId: workerData.jobId,
        result,
        timestamp: new Date().toISOString(),
      });
    }

    return result;
  } catch (error) {
    // Send error message
    if (parentPort) {
      parentPort.postMessage({
        type: 'error',
        jobId: workerData.jobId,
        error: {
          message: error.message,
          stack: error.stack,
        },
        timestamp: new Date().toISOString(),
      });
    }

    throw error;
  }
}

// Run the job
runJob().catch((error) => {
  console.error('Worker execution failed:', error);
  process.exit(1);
});
`;

    // Write worker file
    writeFileSync(workerPath, workerContent.trim(), "utf8");
    this.createdWorkerFiles.add(workerPath); // Track for cleanup
    logger.debug(`Created worker file: ${workerPath}`);

    return workerPath;
  }

  /**
   * Schedule a job with Bree
   */
  async scheduleJob(jobDef, options = {}) {
    const breeConfig = this.toBreeJobConfig(jobDef, options);
    await this.scheduler.addJob(breeConfig);
    logger.info(`Job scheduled: ${breeConfig.name}`);
    return breeConfig;
  }

  /**
   * Unschedule a job
   */
  async unscheduleJob(jobId) {
    await this.scheduler.removeJob(jobId);
    logger.info(`Job unscheduled: ${jobId}`);
  }

  /**
   * Execute a job with locking and receipts
   */
  async executeJobWithLock(jobDef, options = {}) {
    const { payload = {}, context = {}, force = false } = options;
    const jobId = jobDef.id || jobDef.name || jobDef.meta?.name;
    const lockName = `job-${jobId}`;

    const startTime = Date.now();
    const startedAt = new Date().toISOString();

    let lockAcquired = false;

    try {
      // Acquire lock
      lockAcquired = await this.lock.acquire(lockName, { ttl: 300000 }); // 5 min TTL
      if (!lockAcquired && !force) {
        throw new Error(`Job ${jobId} is already running`);
      }

      // Build execution context
      const gitInfo = await this.git.info();
      const execContext = {
        ...context,
        cwd: this.cwd,
        env: {
          TZ: "UTC",
          LANG: "C",
          ...process.env,
          ...context.env,
        },
        git: gitInfo,
        payload,
      };

      // Store context for worker
      this.jobContexts.set(jobId, execContext);

      // Update worker data with context
      const breeConfig = this.toBreeJobConfig(jobDef, options);
      if (breeConfig.worker) {
        breeConfig.worker.workerData = {
          ...breeConfig.worker.workerData,
          context: execContext,
          payload,
        };
      }

      // Add job to scheduler if not already added
      if (!this.scheduler.hasJob(jobId)) {
        await this.scheduler.addJob(breeConfig);
      }

      // Run the job (Bree.run() waits for completion)
      // Note: Bree's run() method is async and waits for the worker to complete
      try {
        await this.scheduler.runJob(jobId);
      } catch (error) {
        throw error;
      }

      const finishedAt = new Date().toISOString();
      const duration = Date.now() - startTime;

      // Write receipt
      await this.receipt.write({
        jobId,
        fingerprint: this.generateFingerprint(jobId, gitInfo.head, payload),
        startedAt,
        finishedAt,
        head: gitInfo.head,
        ok: true,
        result: jobResult,
        duration,
      });

      return {
        ok: true,
        result: jobResult,
        duration,
        startedAt,
        finishedAt,
      };
    } catch (error) {
      const finishedAt = new Date().toISOString();
      const duration = Date.now() - startTime;

      // Write error receipt
      const gitInfo = await this.git.info();
      await this.receipt.write({
        jobId,
        fingerprint: this.generateFingerprint(jobId, gitInfo.head, payload),
        startedAt,
        finishedAt,
        head: gitInfo.head,
        ok: false,
        error: error.message,
        duration,
      });

      throw error;
    } finally {
      // Always release lock
      if (lockAcquired) {
        await this.lock.release(lockName);
      }

      // Clean up context
      this.jobContexts.delete(jobId);
    }
  }

  /**
   * Generate execution fingerprint
   */
  generateFingerprint(jobId, head, payload) {
    const payloadHash = payload
      ? createHash("sha256").update(JSON.stringify(payload)).digest("hex")
      : "";
    const data = `${jobId}@${head}@${payloadHash}`;
    return createHash("sha256").update(data).digest("hex").slice(0, 16);
  }

  /**
   * Start the scheduler
   */
  async start() {
    await this.scheduler.start();
  }

  /**
   * Stop the scheduler
   */
  async stop() {
    await this.scheduler.stop();
  }

  /**
   * Get scheduler status
   */
  getStatus() {
    return this.scheduler.getStatus();
  }

  /**
   * Shutdown the bridge and scheduler
   */
  async shutdown() {
    try {
      await this.scheduler.shutdown();
    } catch (error) {
      logger.warn("Error shutting down scheduler:", error.message);
    }

    // Clean up created worker files
    for (const workerFile of this.createdWorkerFiles) {
      try {
        if (existsSync(workerFile)) {
          rmSync(workerFile);
          logger.debug(`Cleaned up worker file: ${workerFile}`);
        }
      } catch (error) {
        logger.warn(`Failed to cleanup worker file ${workerFile}:`, error.message);
      }
    }
    this.createdWorkerFiles.clear();

    // Clean up contexts
    this.jobContexts.clear();
  }
}

// Singleton instances keyed by cwd
const bridgeInstances = new Map();

/**
 * Get or create the JobBridge singleton for a specific cwd
 */
export function getJobBridge(options = {}) {
  const cwd = options.cwd || process.cwd();

  if (!bridgeInstances.has(cwd)) {
    bridgeInstances.set(cwd, new JobBridge(options));
  }

  return bridgeInstances.get(cwd);
}

/**
 * Reset the bridge singleton for a specific cwd (mainly for testing)
 */
export function resetJobBridge(cwd = null) {
  if (cwd) {
    // Reset specific cwd
    if (bridgeInstances.has(cwd)) {
      const instance = bridgeInstances.get(cwd);
      instance.shutdown().catch((error) => {
        logger.error("Error resetting job bridge:", error.message);
      });
      bridgeInstances.delete(cwd);
    }
  } else {
    // Reset all instances
    for (const [key, instance] of bridgeInstances.entries()) {
      instance.shutdown().catch((error) => {
        logger.error("Error resetting job bridge:", error.message);
      });
      bridgeInstances.delete(key);
    }
  }
}

export default JobBridge;
