// src/jobs/job-bridge.mjs
// GitVan v3.0.0 — Job Bridge
// Adapts between GitVan job interface and Bree scheduler

import { join } from "pathe";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { getBreeScheduler } from "./bree-scheduler.mjs";
import { useLock } from "../composables/lock.mjs";
import { useReceipt } from "../composables/receipt.mjs";
import { useGit } from "../composables/git/index.mjs";
import { createLogger } from "../utils/logger.mjs";

const logger = createLogger("jobs:bridge");

/**
 * Job Bridge
 * Converts GitVan job definitions to Bree-compatible format
 * Handles context passing, locking, and receipts
 */
export class JobBridge {
  constructor(options = {}) {
    this.cwd = options.cwd || process.cwd();
    this.scheduler = getBreeScheduler({ cwd: this.cwd, ...options });
    this.lock = useLock();
    this.receipt = useReceipt();
    this.git = useGit();
    this.workerDir = options.workerDir || join(this.cwd, ".gitvan", "workers");
    this.jobContexts = new Map();

    // Ensure worker directory exists
    if (!existsSync(this.workerDir)) {
      mkdirSync(this.workerDir, { recursive: true });
    }
  }

  /**
   * Convert GitVan job definition to Bree job config
   */
  toBreeJobConfig(jobDef, options = {}) {
    const { cron, interval, timeout } = options;

    // Determine scheduling config from job definition or options
    const scheduleConfig = {};
    if (jobDef.cron || cron) {
      scheduleConfig.cron = jobDef.cron || cron;
    } else if (jobDef.interval || interval) {
      scheduleConfig.interval = jobDef.interval || interval;
    }

    // Create worker path
    const workerPath = this.createWorkerFile(jobDef);

    return {
      name: jobDef.id || jobDef.name || jobDef.meta?.name,
      path: workerPath,
      ...scheduleConfig,
      ...(timeout ? { timeout } : {}),
      worker: {
        workerData: {
          jobId: jobDef.id || jobDef.name || jobDef.meta?.name,
          jobFile: jobDef.file,
          meta: jobDef.meta,
        },
      },
    };
  }

  /**
   * Create a worker file for the job
   * Worker files are ES modules that Bree can execute in worker threads
   */
  createWorkerFile(jobDef) {
    const jobId = jobDef.id || jobDef.name || jobDef.meta?.name;
    const workerFileName = `${jobId.replace(/[:/]/g, "-")}-worker.mjs`;
    const workerPath = join(this.workerDir, workerFileName);

    // Worker template that imports and executes the job
    const workerContent = `
// Auto-generated worker for job: ${jobId}
// Generated by GitVan Job Bridge
import { parentPort, workerData } from 'worker_threads';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function runJob() {
  try {
    // Import the job definition
    const jobModule = await import('${jobDef.file.replace(/\\/g, "/")}');

    // Get the job definition
    const jobDef = jobModule.default || jobModule;

    // Get run function
    const runFn = jobDef.run || jobDef;

    if (typeof runFn !== 'function') {
      throw new Error('Job does not export a run function');
    }

    // Get context from workerData
    const context = workerData.context || {};
    const payload = workerData.payload || {};

    // Execute the job
    const result = await runFn({ payload, ctx: context, context });

    // Send success message
    if (parentPort) {
      parentPort.postMessage({
        type: 'success',
        jobId: workerData.jobId,
        result,
        timestamp: new Date().toISOString(),
      });
    }

    return result;
  } catch (error) {
    // Send error message
    if (parentPort) {
      parentPort.postMessage({
        type: 'error',
        jobId: workerData.jobId,
        error: {
          message: error.message,
          stack: error.stack,
        },
        timestamp: new Date().toISOString(),
      });
    }

    throw error;
  }
}

// Run the job
runJob().catch((error) => {
  console.error('Worker execution failed:', error);
  process.exit(1);
});
`;

    // Write worker file
    writeFileSync(workerPath, workerContent.trim(), "utf8");
    logger.debug(`Created worker file: ${workerPath}`);

    return workerPath;
  }

  /**
   * Schedule a job with Bree
   */
  async scheduleJob(jobDef, options = {}) {
    const breeConfig = this.toBreeJobConfig(jobDef, options);
    await this.scheduler.addJob(breeConfig);
    logger.info(`Job scheduled: ${breeConfig.name}`);
    return breeConfig;
  }

  /**
   * Unschedule a job
   */
  async unscheduleJob(jobId) {
    await this.scheduler.removeJob(jobId);
    logger.info(`Job unscheduled: ${jobId}`);
  }

  /**
   * Execute a job with locking and receipts
   */
  async executeJobWithLock(jobDef, options = {}) {
    const { payload = {}, context = {}, force = false } = options;
    const jobId = jobDef.id || jobDef.name || jobDef.meta?.name;
    const lockName = `job-${jobId}`;

    const startTime = Date.now();
    const startedAt = new Date().toISOString();

    let lockAcquired = false;

    try {
      // Acquire lock
      lockAcquired = await this.lock.acquire(lockName, { ttl: 300000 }); // 5 min TTL
      if (!lockAcquired && !force) {
        throw new Error(`Job ${jobId} is already running`);
      }

      // Build execution context
      const gitInfo = await this.git.info();
      const execContext = {
        ...context,
        cwd: this.cwd,
        env: {
          TZ: "UTC",
          LANG: "C",
          ...process.env,
          ...context.env,
        },
        git: gitInfo,
        payload,
      };

      // Store context for worker
      this.jobContexts.set(jobId, execContext);

      // Update worker data with context
      const breeConfig = this.toBreeJobConfig(jobDef, options);
      if (breeConfig.worker) {
        breeConfig.worker.workerData = {
          ...breeConfig.worker.workerData,
          context: execContext,
          payload,
        };
      }

      // Add job to scheduler if not already added
      if (!this.scheduler.hasJob(jobId)) {
        await this.scheduler.addJob(breeConfig);
      }

      // Register message handler for job results
      let jobResult = null;
      let jobError = null;

      this.scheduler.onWorkerMessage(jobId, (message) => {
        if (message.type === "success") {
          jobResult = message.result;
        } else if (message.type === "error") {
          jobError = new Error(message.error.message);
          jobError.stack = message.error.stack;
        }
      });

      // Run the job
      await this.scheduler.runJob(jobId);

      // Wait for job completion (check for result or error)
      const maxWaitTime = 60000; // 1 minute timeout
      const startWait = Date.now();
      while (!jobResult && !jobError && Date.now() - startWait < maxWaitTime) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }

      if (jobError) {
        throw jobError;
      }

      const finishedAt = new Date().toISOString();
      const duration = Date.now() - startTime;

      // Write receipt
      await this.receipt.write({
        jobId,
        fingerprint: this.generateFingerprint(jobId, gitInfo.head, payload),
        startedAt,
        finishedAt,
        head: gitInfo.head,
        ok: true,
        result: jobResult,
        duration,
      });

      return {
        ok: true,
        result: jobResult,
        duration,
        startedAt,
        finishedAt,
      };
    } catch (error) {
      const finishedAt = new Date().toISOString();
      const duration = Date.now() - startTime;

      // Write error receipt
      const gitInfo = await this.git.info();
      await this.receipt.write({
        jobId,
        fingerprint: this.generateFingerprint(jobId, gitInfo.head, payload),
        startedAt,
        finishedAt,
        head: gitInfo.head,
        ok: false,
        error: error.message,
        duration,
      });

      throw error;
    } finally {
      // Always release lock
      if (lockAcquired) {
        await this.lock.release(lockName);
      }

      // Clean up context
      this.jobContexts.delete(jobId);
    }
  }

  /**
   * Generate execution fingerprint
   */
  generateFingerprint(jobId, head, payload) {
    const crypto = await import("node:crypto");
    const payloadHash = payload
      ? crypto.createHash("sha256").update(JSON.stringify(payload)).digest("hex")
      : "";
    const data = `${jobId}@${head}@${payloadHash}`;
    return crypto.createHash("sha256").update(data).digest("hex").slice(0, 16);
  }

  /**
   * Start the scheduler
   */
  async start() {
    await this.scheduler.start();
  }

  /**
   * Stop the scheduler
   */
  async stop() {
    await this.scheduler.stop();
  }

  /**
   * Get scheduler status
   */
  getStatus() {
    return this.scheduler.getStatus();
  }

  /**
   * Shutdown the bridge and scheduler
   */
  async shutdown() {
    await this.scheduler.shutdown();
    this.jobContexts.clear();
  }
}

// Singleton instance
let bridgeInstance = null;

/**
 * Get or create the JobBridge singleton
 */
export function getJobBridge(options = {}) {
  if (!bridgeInstance) {
    bridgeInstance = new JobBridge(options);
  }
  return bridgeInstance;
}

/**
 * Reset the bridge singleton (mainly for testing)
 */
export function resetJobBridge() {
  if (bridgeInstance) {
    bridgeInstance.shutdown().catch((error) => {
      logger.error("Error resetting job bridge:", error.message);
    });
    bridgeInstance = null;
  }
}

export default JobBridge;
