/**
 * Cleanroom test suite definitions
 * Extracted from CleanroomTesting class for maintainability
 */

export function getCoreTests() {
  return [
    {
      name: "CLI Help Command",
      command: "node /gitvan/dist/bin/gitvan.mjs --help",
    },
    {
      name: "Project Initialization",
      command:
        "node /gitvan/dist/bin/gitvan.mjs init --name cleanroom-test --description 'Cleanroom test project'",
    },
    {
      name: "Git Repository Setup",
      command:
        "git init && echo 'test content' > test.txt && git add test.txt && git commit -m 'Initial commit'",
    },
    {
      name: "Configuration Loading",
      command: "test -f gitvan.config.js && test -f package.json",
    },
  ];
}

export function getAITests() {
  return [
    {
      name: "Chat Command Help",
      command: "node /gitvan/dist/bin/gitvan.mjs chat help",
    },
    {
      name: "Chat Generate (Fallback)",
      command:
        "node /gitvan/dist/bin/gitvan.mjs chat generate --prompt 'Create a simple test job'",
    },
    {
      name: "AI Template Loop",
      command:
        "node /gitvan/dist/bin/gitvan.mjs chat template 'Create a React component'",
    },
  ];
}

export function getWorkflowTests() {
  return [
    {
      name: "Workflow Help",
      command: "node /gitvan/dist/bin/gitvan.mjs workflow help",
    },
    {
      name: "Workflow List",
      command: "node /gitvan/dist/bin/gitvan.mjs workflow list",
    },
    {
      name: "Workflow Directory Structure",
      command: "test -d workflows && test -f workflows/README.md",
    },
  ];
}

export function getHooksTests() {
  return [
    {
      name: "Hooks Help",
      command: "node /gitvan/dist/bin/gitvan.mjs hooks help",
    },
    {
      name: "Hooks List",
      command: "node /gitvan/dist/bin/gitvan.mjs hooks list",
    },
    {
      name: "Hooks Stats",
      command: "node /gitvan/dist/bin/gitvan.mjs hooks stats",
    },
    {
      name: "Hooks Directory Structure",
      command: "test -d hooks && test -f hooks/README.md",
    },
  ];
}

export function getJTBDTests() {
  return [
    {
      name: "JTBD Help",
      command: "node /gitvan/dist/bin/gitvan.mjs jtbd help",
    },
    {
      name: "JTBD List",
      command: "node /gitvan/dist/bin/gitvan.mjs jtbd list",
    },
    {
      name: "JTBD Stats",
      command: "node /gitvan/dist/bin/gitvan.mjs jtbd stats",
    },
    {
      name: "JTBD Create Hook",
      command:
        "node /gitvan/dist/bin/gitvan.mjs jtbd create test-hook 'Test Hook' ask",
    },
    {
      name: "JTBD Directory Structure",
      command: "test -d hooks/jtbd-hooks || mkdir -p hooks/jtbd-hooks",
    },
  ];
}

export function getAllTests() {
  return [
    ...getCoreTests(),
    ...getAITests(),
    ...getWorkflowTests(),
    ...getHooksTests(),
    ...getJTBDTests(),
  ];
}

export function generateMarkdownReport(summary, results) {
  return `# GitVan Cleanroom Test Report

## Summary
- **Total Tests**: ${summary.totalTests}
- **Passed**: ${summary.passedTests}
- **Failed**: ${summary.failedTests}
- **Success Rate**: ${summary.successRate.toFixed(1)}%
- **Test Suites**: ${summary.testSuites}

## Test Results

${results
  .map(
    (result) => `
### ${result.suite} Suite
- **Image**: ${result.image}
- **Timestamp**: ${result.timestamp}
- **Tests**: ${result.summary.total} (${result.summary.passed} passed, ${
      result.summary.failed
    } failed)

#### Test Details
${result.tests
  .map(
    (test) => `
- **${test.name}**: ${test.success ? "PASSED" : "FAILED"} (${
      test.duration
    }ms)
  ${!test.success ? `  - Error: ${test.error}` : ""}
`
  )
  .join("")}
`
  )
  .join("")}

---
*Generated by GitVan Cleanroom Testing Utilities*
`;
}

export function generateHTMLReport(summary, results) {
  return `<!DOCTYPE html>
<html>
<head>
    <title>GitVan Cleanroom Test Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 5px; }
        .test-suite { margin: 20px 0; padding: 15px; border: 1px solid #ddd; }
        .passed { color: green; }
        .failed { color: red; }
    </style>
</head>
<body>
    <h1>GitVan Cleanroom Test Report</h1>
    <div class="summary">
        <h2>Summary</h2>
        <p>Total Tests: ${summary.totalTests}</p>
        <p>Passed: <span class="passed">${summary.passedTests}</span></p>
        <p>Failed: <span class="failed">${summary.failedTests}</span></p>
        <p>Success Rate: ${summary.successRate.toFixed(1)}%</p>
    </div>

    ${results
      .map(
        (result) => `
    <div class="test-suite">
        <h3>${result.suite} Suite</h3>
        <p>Image: ${result.image}</p>
        <p>Tests: ${result.summary.total} (${result.summary.passed} passed, ${
          result.summary.failed
        } failed)</p>

        <ul>
        ${result.tests
          .map(
            (test) => `
            <li class="${test.success ? "passed" : "failed"}">
                ${test.name}: ${test.success ? "PASSED" : "FAILED"} (${
              test.duration
            }ms)
                ${
                  !test.success ? `<br><small>Error: ${test.error}</small>` : ""
                }
            </li>
        `
          )
          .join("")}
        </ul>
    </div>
    `
      )
      .join("")}
</body>
</html>`;
}

export function calculateSummary(results) {
  const totalTests = results.reduce(
    (sum, result) => sum + result.summary.total, 0
  );
  const passedTests = results.reduce(
    (sum, result) => sum + result.summary.passed, 0
  );
  const failedTests = results.reduce(
    (sum, result) => sum + result.summary.failed, 0
  );

  return {
    totalTests,
    passedTests,
    failedTests,
    successRate: totalTests > 0 ? (passedTests / totalTests) * 100 : 0,
    testSuites: results.length,
  };
}
