name: checks
on: { push: {}, pull_request: {} }
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm test
      - run: pnpm test:docs
      # - uses: codecov/codecov-action@v5
      #   with: { token: "${{ secrets.CODECOV_TOKEN }}" }
