name: Release Test - Clean Room Install

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test (e.g., 2.0.0)"
        required: true
        default: "2.0.0"

jobs:
  clean-room-test:
    name: Clean Room Install Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-manager: [npm, pnpm, yarn]
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Package Manager
        run: |
          if [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            npm install -g pnpm
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            npm install -g yarn
          fi

      - name: Get Version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Create Clean Test Directory
        run: |
          mkdir -p /tmp/gitvan-test
          cd /tmp/gitvan-test
          echo "Test directory: $(pwd)"

      - name: Install GitVan from npm
        run: |
          cd /tmp/gitvan-test
          echo "Installing gitvan@${{ steps.version.outputs.version }} with ${{ matrix.package-manager }}"

          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm init -y
            npm install gitvan@${{ steps.version.outputs.version }}
          elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            pnpm init -y
            pnpm add gitvan@${{ steps.version.outputs.version }}
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            yarn init -y
            yarn add gitvan@${{ steps.version.outputs.version }}
          fi

      - name: Verify Installation
        run: |
          cd /tmp/gitvan-test
          echo "Verifying installation..."

          # Check that gitvan binary exists and is executable
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            CLI_PATH="./node_modules/.bin/gitvan"
          elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            CLI_PATH="./node_modules/.bin/gitvan"
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            CLI_PATH="./node_modules/.bin/gitvan"
          fi

          if [ ! -f "$CLI_PATH" ]; then
            echo "❌ GitVan CLI not found at $CLI_PATH"
            exit 1
          fi

          if [ ! -x "$CLI_PATH" ]; then
            echo "❌ GitVan CLI not executable at $CLI_PATH"
            exit 1
          fi

          echo "✅ GitVan CLI found and executable"

      - name: Test Version Command
        run: |
          cd /tmp/gitvan-test
          echo "Testing version command..."

          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            VERSION_OUTPUT=$(npx gitvan --version)
          elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            VERSION_OUTPUT=$(pnpm exec gitvan --version)
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            VERSION_OUTPUT=$(yarn exec gitvan --version)
          fi

          echo "Version output: $VERSION_OUTPUT"

          if [ "$VERSION_OUTPUT" != "${{ steps.version.outputs.version }}" ]; then
            echo "❌ Version mismatch! Expected: ${{ steps.version.outputs.version }}, Got: $VERSION_OUTPUT"
            exit 1
          fi

          echo "✅ Version command works correctly"

      - name: Test Basic Commands
        run: |
          cd /tmp/gitvan-test
          echo "Testing basic commands..."

          # Initialize git repo
          git init
          git config user.name "Test User"
          git config user.email "test@example.com"

          # Test help command
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npx gitvan help > /dev/null
          elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            pnpm exec gitvan help > /dev/null
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            yarn exec gitvan help > /dev/null
          fi

          echo "✅ Help command works"

      - name: Test Init Command
        run: |
          cd /tmp/gitvan-test
          echo "Testing init command..."

          # Test init command (should work in clean environment)
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npx gitvan init --help > /dev/null
          elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            pnpm exec gitvan init --help > /dev/null
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            yarn exec gitvan init --help > /dev/null
          fi

          echo "✅ Init command works"

      - name: Test Hook Installation
        run: |
          cd /tmp/gitvan-test
          echo "Testing hook installation..."

          # Create a test file
          echo "test" > test.txt
          git add test.txt
          git commit -m "test commit"

          # Test ensure command (hook installation)
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npx gitvan ensure --help > /dev/null
          elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
            pnpm exec gitvan ensure --help > /dev/null
          elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
            yarn exec gitvan ensure --help > /dev/null
          fi

          echo "✅ Ensure command works"

      - name: Verify Dependencies
        run: |
          cd /tmp/gitvan-test
          echo "Verifying all runtime dependencies are installed..."

          # Check that all required dependencies are present
          REQUIRED_DEPS=(
            "@babel/parser"
            "@babel/traverse"
            "ai"
            "c12"
            "cacache"
            "citty"
            "consola"
            "defu"
            "fuse.js"
            "giget"
            "gray-matter"
            "hookable"
            "inflection"
            "klona"
            "lru-cache"
            "minimatch"
            "node-cron"
            "nunjucks"
            "ollama"
            "pathe"
            "prompts"
            "semver"
            "toml"
            "unctx"
            "zod"
          )

          for dep in "${REQUIRED_DEPS[@]}"; do
            if [ "${{ matrix.package-manager }}" = "npm" ]; then
              if ! npm list "$dep" > /dev/null 2>&1; then
                echo "❌ Missing dependency: $dep"
                exit 1
              fi
            elif [ "${{ matrix.package-manager }}" = "pnpm" ]; then
              if ! pnpm list "$dep" > /dev/null 2>&1; then
                echo "❌ Missing dependency: $dep"
                exit 1
              fi
            elif [ "${{ matrix.package-manager }}" = "yarn" ]; then
              if ! yarn list --pattern "$dep" > /dev/null 2>&1; then
                echo "❌ Missing dependency: $dep"
                exit 1
              fi
            fi
          done

          echo "✅ All runtime dependencies are present"

      - name: Test Package Contents
        run: |
          cd /tmp/gitvan-test
          echo "Testing package contents..."

          # Check that bin files are present
          if [ ! -f "./node_modules/gitvan/bin/gitvan.mjs" ]; then
            echo "❌ Main CLI file missing"
            exit 1
          fi

          if [ ! -f "./node_modules/gitvan/bin/git-hook-handler.mjs" ]; then
            echo "❌ Hook handler missing"
            exit 1
          fi

          if [ ! -f "./node_modules/gitvan/bin/git-hooks-setup.mjs" ]; then
            echo "❌ Hook setup missing"
            exit 1
          fi

          echo "✅ All required files are present"

      - name: Cleanup
        if: always()
        run: |
          rm -rf /tmp/gitvan-test
          echo "Cleanup completed"
